dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:

before_script:
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run --config=.golangci-lint.yaml

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  # build the executable
  - CGO_ENABLED=0 GOOS=linux go build -o ./build/api/api ./cmd/api
  - export docker_repo=xanderflood/plaid-ui
  - export docker_build_directory=./build/api

  # build and push the base image
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`
  - export tmpname="local"
  - export dockerfile="Dockerfile"
  - export tags="build-${TRAVIS_BUILD_NUMBER},commit-${TRAVIS_COMMIT::8},$TAG"
  - ./build_and_push_image.sh

  # build and push the swarm-focused image
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "swarm"; else echo "swarm-staging" ; fi`
  - export tmpname="swarm-local"
  - export dockerfile="swarm.Dockerfile"
  - export tags="build-${TRAVIS_BUILD_NUMBER},commit-${TRAVIS_COMMIT::8},$TAG"
  - ./build_and_push_image.sh
