dist: xenial

language: go

env:
  - GO111MODULE=on
  - REPO=smartatransit/scrapedumper

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:

before_script:
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run --config=.golangci-lint.yaml
  - cd build/api && GOOS=linux go build # target the container environment

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - cd build/api && docker build . -t $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER ${TRAVIS_COMMIT::8}
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER $REPO:$TRAVIS_BRANCH
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER $REPO:$TAG

  - docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:${TRAVIS_COMMIT::8}
  - docker push $REPO:$TRAVIS_BRANCH
  - docker push $REPO:$TAG
