dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

# TODO change back to before_script?
after_script:
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run --config=.golangci-lint.yaml

script: ./.travis_build.sh
