dist: xenial

language: go

env:
  - GO111MODULE=on
  - REPO=smartatransit/scrapedumper

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

before_script:
  - golangci-lint run --config=.golangci-lint.yaml # run a bunch of code checkers/linters in parallel
  - cd build/api && GOOS=linux go build # target the container environment

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - cd build/api && docker build . -t $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER ${TRAVIS_COMMIT::8}
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER $REPO:$TRAVIS_BRANCH
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER $REPO:$TAG

  - docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:${TRAVIS_COMMIT::8}
  - docker push $REPO:$TRAVIS_BRANCH
  - docker push $REPO:$TAG
